#!/bin/bash

source "${BASH_SOURCE[0]}.cfg"

bold=$(tty -s && tput bold)
regular=$(tty -s && tput sgr0)
underline=$(tty -s && tput smul)
error=$(tty -s && tput setaf 1)

deploy() {
    source="$1"
    shift
    if [ ${server} = "go" ]; then 
        go run tools/server.go ${source} --port ${port} --redirect-map redirect.map --browse 
    elif [ ${server} = "python" ]; then
        python tools/server.py ${source} --port ${port} --redirect-map redirect.map --browse 
    else
        node tools/server.js ${source} --port ${port} --redirect-map redirect.map --browse 
    fi
}

command="$1"
shift
case "${command}" in
    "deploy") deploy $@;;
    "log") echo "Not supported for local deployment.";;
    "console") echo "Not supported for local deployment.";;
esac
