#!/bin/bash

source "${BASH_SOURCE[0]}.cfg"

bold=$(tty -s && tput bold)
regular=$(tty -s && tput sgr0)
underline=$(tty -s && tput smul)
error=$(tty -s && tput setaf 1)

deploy() {
    source="$1"
    shift
    echo "${bold}aws s3 rm -r *${regular}"
    aws s3 rm --recursive s3://${bucket} --region ${region}
    echo "${bold}aws s3 cp -r ${source} *${regular}"
    aws s3 cp --recursive ${source} s3://${bucket} --region ${region}
}

command="$1"
shift
case "${command}" in
    "deploy") deploy $@;;
    "log") echo "Not supported for S3.";;
    "console") echo "Not supported for S3.";;
esac
