#!/bin/bash

source "${BASH_SOURCE[0]}.cfg"

bold=$(tty -s && tput bold)
regular=$(tty -s && tput sgr0)
underline=$(tty -s && tput smul)
error=$(tty -s && tput setaf 1)

if [ ! -z "${region}" ]; then
    region="--region ${region}"
fi

deploy() {
    source="$1"
    shift
    echo "${bold}aws s3 rm --recursive s3://${bucket} ${region}${regular}"
    aws s3 rm --recursive s3://${bucket} ${region}
    echo "${bold}aws s3 cp --recursive ${source} s3://${bucket} ${region}${regular}"
    aws s3 cp --recursive ${source} s3://${bucket} ${region}
}

console() {
    url="https://s3.console.aws.amazon.com/s3/buckets/${bucket}"
    case "$(uname -s)" in
        Darwin*) open ${url};;
        Linux*) xdg-open ${url};;
        MINGW*) start "" ${url};;
    esac
}

command="$1"
shift
case "${command}" in
    "deploy") deploy $@;;
    "log") echo "Not supported for S3.";;
    "console") console;;
esac
